workflows:
  ios-release:
    name: iOS Release
    max_build_duration: 60
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.ipca.digiConnect
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Disable Swift Package Manager
        script: flutter config --no-enable-swift-package-manager
      - name: Get Flutter packages
        script: flutter pub get
      - name: Install CocoaPods
        script: |
          cd ios && pod install
      - name: Build iOS release IPA
        script: |
          flutter build ipa --release \
            --build-name=1.7.4 \
            --build-number=$BUILD_NUMBER \
            --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: Y34L3DZ4CF
        issuer_id: 69a6de76-e283-47e3-e053-5b8c7c11a4d1
        submit_to_testflight: true
